language: node_js
node_js:
  - '12'
stages:
  - Code Quality
  - Unit Tests
  - Integration Tests
script: skip

jobs:
    include:
        - stage: Code Quality
          if: branch = master OR type = pull_request
          script: yarn quality
        - stage: Unit Tests
          if: branch = master OR type = pull_request
          before_install: yarn global add codecov coveralls
          script: yarn test:unit
          after_success: codecov && coveralls < coverage/lcov.info
        - stage: Integration Tests
          if: branch = master OR type = pull_request
          script: yarn test:integration
cache:
    yarn: true
notifications:
    email: false
